### ISSUE TITLE
Version 0.2.0 tag

### ISSUE THREAD

**Issue by nouwaarom** [stephenmathieson/case.c#7]
Hey, I was running `clib` tests on a test version and in one of the tests this package was installed.
However, there was a problem as `clib` expects the version tag without a prefix, but the tag for `0.2.0` does have a prefix. Can you add a tag without a prefix?
```
 test/install-binary-dependencies.sh
       error : unable to fetch https://raw.githubusercontent.com/stephenmathieson/case.c/0.2.0/src/case.c:src/case.c
       error : unable to fetch https://raw.githubusercontent.com/stephenmathieson/case.c/0.2.0/src/case.h:src/case.h
```

**Comment by stephenmathieson** [comment]
Whoops, my bad. https://github.com/stephenmathieson/case.c/releases/tag/0.2.0
